Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,60 +1,60 @@
 #!/usr/bin/env bash
-
-# bin/compile <build-dir> <cache-dir> <env-dir>
-
-# fail hard
-set -o pipefail
-# fail harder
-set -eu
-# move hidden files too, just in case
-shopt -s dotglob
-
-BUILD_DIR=$1
-CACHE_DIR=$2
-
-BUILDPACK=".modperl2-buildpack"
-APACHE_BUNDLE="httpd_2.4.6-mod_perl_2.0.10.tar.gz"
-APACHE_BUNDLE_URL="https://www.webassign.net/zip/${APACHE_BUNDLE}"
-
-cd $BUILD_DIR
-
-mkdir -p $BUILDPACK && cd $BUILDPACK
-
-echo "-----> Bundling Apache"
-
-if [ -d $CACHE_DIR/$BUILDPACK/httpd ]; then
-  echo "--------> from Cache"
-  cp -r $CACHE_DIR/$BUILDPACK/* .
-else
-  echo "--------> from Internet"
-  curl --silent --max-time 60 --location $APACHE_BUNDLE_URL | tar -xz
-  mkdir -p $CACHE_DIR/$BUILDPACK
-  cp -r * $CACHE_DIR/$BUILDPACK
-fi
-
-cd $BUILD_DIR
-
+#
+# # bin/compile <build-dir> <cache-dir> <env-dir>
+#
+# # fail hard
+# set -o pipefail
+# # fail harder
+# set -eu
+# # move hidden files too, just in case
+# shopt -s dotglob
+#
+# BUILD_DIR=$1
+# CACHE_DIR=$2
+#
+# BUILDPACK=".modperl2-buildpack"
+# APACHE_BUNDLE="httpd_2.4.6-mod_perl_2.0.10.tar.gz"
+# APACHE_BUNDLE_URL="https://www.webassign.net/zip/${APACHE_BUNDLE}"
+#
 # cd $BUILD_DIR
 #
-# # move app things to www
-# mkdir -p $CACHE_DIR/www
-# mv * $CACHE_DIR/www
-# if [ -f $CACHE_DIR/www/lib ]; then
-#     mv $CACHE_DIR/www/lib .
+# mkdir -p $BUILDPACK && cd $BUILDPACK
+#
+# echo "-----> Bundling Apache"
+#
+# if [ -d $CACHE_DIR/$BUILDPACK/httpd ]; then
+#   echo "--------> from Cache"
+#   cp -r $CACHE_DIR/$BUILDPACK/* .
+# else
+#   echo "--------> from Internet"
+#   curl --silent --max-time 60 --location $APACHE_BUNDLE_URL | tar -xz
+#   mkdir -p $CACHE_DIR/$BUILDPACK
+#   cp -r * $CACHE_DIR/$BUILDPACK
 # fi
-# mv $CACHE_DIR/www .
-
-APACHE_DIR="$BUILDPACK/httpd"
-
-cat >>boot.sh <<EOF
-sed -i 's/Listen 8123/Listen '\$PORT'/' $APACHE_DIR/conf/httpd.conf
-for var in \`env|cut -f1 -d=\`; do
-  echo "PassEnv \$var" >> $APACHE_DIR/conf/httpd.conf;
-done
-touch $APACHE_DIR/logs/error_log
-touch $APACHE_DIR/logs/access_log
-tail -F $APACHE_DIR/logs/error_log &
-tail -F $APACHE_DIR/logs/access_log &
-echo "Launching Apache"
-exec $APACHE_DIR/bin/httpd -DNO_DETACH
-EOF
+#
+# cd $BUILD_DIR
+#
+# # cd $BUILD_DIR
+# #
+# # # move app things to www
+# # mkdir -p $CACHE_DIR/www
+# # mv * $CACHE_DIR/www
+# # if [ -f $CACHE_DIR/www/lib ]; then
+# #     mv $CACHE_DIR/www/lib .
+# # fi
+# # mv $CACHE_DIR/www .
+#
+# APACHE_DIR="$BUILDPACK/httpd"
+#
+# cat >>boot.sh <<EOF
+# sed -i 's/Listen 8123/Listen '\$PORT'/' $APACHE_DIR/conf/httpd.conf
+# for var in \`env|cut -f1 -d=\`; do
+#   echo "PassEnv \$var" >> $APACHE_DIR/conf/httpd.conf;
+# done
+# touch $APACHE_DIR/logs/error_log
+# touch $APACHE_DIR/logs/access_log
+# tail -F $APACHE_DIR/logs/error_log &
+# tail -F $APACHE_DIR/logs/access_log &
+# echo "Launching Apache"
+# exec $APACHE_DIR/bin/httpd -DNO_DETACH
+# EOF
